package com.example.currencyconverter.models

class DataSample(
    val data: List<SaveCurrency> = listOf(
        SaveCurrency(name = "United Arab Emirates Dirham", code = "AED", rate = 3.961998),
        SaveCurrency(name = "Afghan Afghani", code = "AFN", rate = 72.846592),
        SaveCurrency(name = "Albanian Lek", code = "ALL", rate = 98.300942),
        SaveCurrency(name = "Armenian Dram", code = "AMD", rate = 417.475438),
        SaveCurrency(name = "Netherlands Antillean Guilder", code = "ANG", rate = 1.944341),
        SaveCurrency(name = "Angolan Kwanza", code = "AOA", rate = 980.568776),
        SaveCurrency(name = "Argentine Peso", code = "ARS", rate = 1065.71416),
        SaveCurrency(name = "Australian Dollar", code = "AUD", rate = 1.646605),
        SaveCurrency(name = "Aruban Florin", code = "AWG", rate = 1.944308),
        SaveCurrency(name = "Azerbaijani Manat", code = "AZN", rate = 1.833398),
        SaveCurrency(name = "Bosnia-Herzegovina Convertible Mark", code = "BAM", rate = 1.953831),
        SaveCurrency(name = "Barbadian Dollar", code = "BBD", rate = 2.178285),
        SaveCurrency(name = "Bangladeshi Taka", code = "BDT", rate = 128.920087),
        SaveCurrency(name = "Bulgarian Lev", code = "BGN", rate = 1.955849),
        SaveCurrency(name = "Bahraini Dinar", code = "BHD", rate = 0.406532),
        SaveCurrency(name = "Burundian Franc", code = "BIF", rate = 3135.582122),
        SaveCurrency(name = "Bermudan Dollar", code = "BMD", rate = 1.078673),
        SaveCurrency(name = "Brunei Dollar", code = "BND", rate = 1.429959),
        SaveCurrency(name = "Bolivian Boliviano", code = "BOB", rate = 7.454419),
        SaveCurrency(name = "Brazilian Real", code = "BRL", rate = 6.15717),
        SaveCurrency(name = "Bahamian Dollar", code = "BSD", rate = 1.078803),
        SaveCurrency(name = "Bitcoin", code = "BTC", rate = 1.5060643e-5),
        SaveCurrency(name = "Bhutanese Ngultrum", code = "BTN", rate = 90.686615),
        SaveCurrency(name = "Botswanan Pula", code = "BWP", rate = 14.48134),
        SaveCurrency(name = "New Belarusian Ruble", code = "BYN", rate = 3.530642),
        SaveCurrency(name = "Belarusian Ruble", code = "BYR", rate = 21141.991123),
        SaveCurrency(name = "Belize Dollar", code = "BZD", rate = 2.174588),
        SaveCurrency(name = "Canadian Dollar", code = "CAD", rate = 1.500386),
        SaveCurrency(name = "Congolese Franc", code = "CDF", rate = 3138.938718),
        SaveCurrency(name = "Swiss Franc", code = "CHF", rate = 0.937475),
        SaveCurrency(name = "Chilean Unit of Account (UF)", code = "CLF", rate = 0.037133),
        SaveCurrency(name = "Chilean Peso", code = "CLP", rate = 1024.609982),
        SaveCurrency(name = "Chinese Yuan", code = "CNY", rate = 7.695899),
        SaveCurrency(name = "Chinese Yuan Offshore", code = "CNH", rate = 7.679391),
        SaveCurrency(name = "Colombian Peso", code = "COP", rate = 4696.305006),
        SaveCurrency(name = "Costa Rican Colón", code = "CRC", rate = 553.841891),
        SaveCurrency(name = "Cuban Convertible Peso", code = "CUC", rate = 1.078673),
        SaveCurrency(name = "Cuban Peso", code = "CUP", rate = 28.584835),
        SaveCurrency(name = "Cape Verdean Escudo", code = "CVE", rate = 110.153487),
        SaveCurrency(name = "Czech Republic Koruna", code = "CZK", rate = 25.348491),
        SaveCurrency(name = "Djiboutian Franc", code = "DJF", rate = 192.114624),
        SaveCurrency(name = "Danish Krone", code = "DKK", rate = 7.46043),
        SaveCurrency(name = "Dominican Peso", code = "DOP", rate = 64.974525),
        SaveCurrency(name = "Algerian Dinar", code = "DZD", rate = 144.086299),
        SaveCurrency(name = "Egyptian Pound", code = "EGP", rate = 52.555317),
        SaveCurrency(name = "Eritrean Nakfa", code = "ERN", rate = 16.180095),
        SaveCurrency(name = "Ethiopian Birr", code = "ETB", rate = 128.916895),
        SaveCurrency(name = "Euro", code = "EUR", rate = 1.0),
        SaveCurrency(name = "Fijian Dollar", code = "FJD", rate = 2.455545),
        SaveCurrency(name = "Falkland Islands Pound", code = "FKP", rate = 0.825367),
        SaveCurrency(name = "British Pound Sterling", code = "GBP", rate = 0.830842),
        SaveCurrency(name = "Georgian Lari", code = "GEL", rate = 2.934237),
        SaveCurrency(name = "Guernsey Pound", code = "GGP", rate = 0.825367),
        SaveCurrency(name = "Ghanaian Cedi", code = "GHS", rate = 17.531171),
        SaveCurrency(name = "Gibraltar Pound", code = "GIP", rate = 0.825367),
        SaveCurrency(name = "Gambian Dalasi", code = "GMD", rate = 75.507),
        SaveCurrency(name = "Guinean Franc", code = "GNF", rate = 9304.62369),
        SaveCurrency(name = "Guatemalan Quetzal", code = "GTQ", rate = 8.339596),
        SaveCurrency(name = "Guyanaese Dollar", code = "GYD", rate = 225.710458),
        SaveCurrency(name = "Hong Kong Dollar", code = "HKD", rate = 8.381694),
        SaveCurrency(name = "Honduran Lempira", code = "HNL", rate = 27.214576),
        SaveCurrency(name = "Croatian Kuna", code = "HRK", rate = 7.431011),
        SaveCurrency(name = "Haitian Gourde", code = "HTG", rate = 142.176728),
        SaveCurrency(name = "Hungarian Forint", code = "HUF", rate = 404.966711),
        SaveCurrency(name = "Indonesian Rupiah", code = "IDR", rate = 17005.010436),
        SaveCurrency(name = "Israeli New Sheqel", code = "ILS", rate = 4.026741),
        SaveCurrency(name = "Manx pound", code = "IMP", rate = 0.825367),
        SaveCurrency(name = "Indian Rupee", code = "INR", rate = 90.68295),
        SaveCurrency(name = "Iraqi Dinar", code = "IQD", rate = 1413.275836),
        SaveCurrency(name = "Iranian Rial", code = "IRR", rate = 45404.040442),
        SaveCurrency(name = "Icelandic Króna", code = "ISK", rate = 148.478875),
        SaveCurrency(name = "Jersey Pound", code = "JEP", rate = 0.825367),
        SaveCurrency(name = "Jamaican Dollar", code = "JMD", rate = 170.678007),
        SaveCurrency(name = "Jordanian Dinar", code = "JOD", rate = 0.764674),
        SaveCurrency(name = "Japanese Yen", code = "JPY", rate = 165.708445),
        SaveCurrency(name = "Kenyan Shilling", code = "KES", rate = 139.310165),
        SaveCurrency(name = "Kyrgystani Som", code = "KGS", rate = 92.551074),
        SaveCurrency(name = "Cambodian Riel", code = "KHR", rate = 4385.4994),
        SaveCurrency(name = "Comorian Franc", code = "KMF", rate = 491.065803),
        SaveCurrency(name = "North Korean Won", code = "KPW", rate = 970.805472),
        SaveCurrency(name = "South Korean Won", code = "KRW", rate = 1495.97934),
        SaveCurrency(name = "Kuwaiti Dinar", code = "KWD", rate = 0.330732),
        SaveCurrency(name = "Cayman Islands Dollar", code = "KYD", rate = 0.899094),
        SaveCurrency(name = "Kazakhstani Tenge", code = "KZT", rate = 528.857068),
        SaveCurrency(name = "Laotian Kip", code = "LAK", rate = 23650.947576),
        SaveCurrency(name = "Lebanese Pound", code = "LBP", rate = 96662.996145),
        SaveCurrency(name = "Sri Lankan Rupee", code = "LKR", rate = 316.820738),
        SaveCurrency(name = "Liberian Dollar", code = "LRD", rate = 207.139344),
        SaveCurrency(name = "Lesotho Loti", code = "LSL", rate = 19.108444),
        SaveCurrency(name = "Lithuanian Litas", code = "LTL", rate = 3.185041),
        SaveCurrency(name = "Latvian Lats", code = "LVL", rate = 0.652478),
        SaveCurrency(name = "Libyan Dinar", code = "LYD", rate = 5.207728),
        SaveCurrency(name = "Moroccan Dirham", code = "MAD", rate = 10.643075),
        SaveCurrency(name = "Moldovan Leu", code = "MDL", rate = 19.338512),
        SaveCurrency(name = "Malagasy Ariary", code = "MGA", rate = 4986.928418),
        SaveCurrency(name = "Macedonian Denar", code = "MKD", rate = 61.539579),
        SaveCurrency(name = "Myanma Kyat", code = "MMK", rate = 3503.487881),
        SaveCurrency(name = "Mongolian Tugrik", code = "MNT", rate = 3665.33094),
        SaveCurrency(name = "Macanese Pataca", code = "MOP", rate = 8.63322),
        SaveCurrency(name = "Mauritanian Ouguiya", code = "MRU", rate = 42.657014),
        SaveCurrency(name = "Mauritian Rupee", code = "MUR", rate = 49.856027),
        SaveCurrency(name = "Maldivian Rufiyaa", code = "MVR", rate = 16.557692),
        SaveCurrency(name = "Malawian Kwacha", code = "MWK", rate = 1870.714872),
        SaveCurrency(name = "Mexican Peso", code = "MXN", rate = 21.577581),
        SaveCurrency(name = "Malaysian Ringgit", code = "MYR", rate = 4.718119),
        SaveCurrency(name = "Mozambican Metical", code = "MZN", rate = 68.92751),
        SaveCurrency(name = "Namibian Dollar", code = "NAD", rate = 19.108444),
        SaveCurrency(name = "Nigerian Naira", code = "NGN", rate = 1772.680442),
        SaveCurrency(name = "Nicaraguan Córdoba", code = "NIO", rate = 39.699994),
        SaveCurrency(name = "Norwegian Krone", code = "NOK", rate = 11.852049),
        SaveCurrency(name = "Nepalese Rupee", code = "NPR", rate = 145.098783),
        SaveCurrency(name = "New Zealand Dollar", code = "NZD", rate = 1.810655),
        SaveCurrency(name = "Omani Rial", code = "OMR", rate = 0.415293),
        SaveCurrency(name = "Panamanian Balboa", code = "PAB", rate = 1.078803),
        SaveCurrency(name = "Peruvian Nuevo Sol", code = "PEN", rate = 4.060708),
        SaveCurrency(name = "Papua New Guinean Kina", code = "PGK", rate = 4.320646),
        SaveCurrency(name = "Philippine Peso", code = "PHP", rate = 62.873154),
        SaveCurrency(name = "Pakistani Rupee", code = "PKR", rate = 299.647244),
        SaveCurrency(name = "Polish Zloty", code = "PLN", rate = 4.343331),
        SaveCurrency(name = "Paraguayan Guarani", code = "PYG", rate = 8588.345486),
        SaveCurrency(name = "Qatari Rial", code = "QAR", rate = 3.933436),
        SaveCurrency(name = "Romanian Leu", code = "RON", rate = 4.974406),
        SaveCurrency(name = "Serbian Dinar", code = "RSD", rate = 117.071651),
        SaveCurrency(name = "Russian Ruble", code = "RUB", rate = 105.014141),
        SaveCurrency(name = "Rwandan Franc", code = "RWF", rate = 1467.207886),
        SaveCurrency(name = "Saudi Riyal", code = "SAR", rate = 4.051023),
        SaveCurrency(name = "Solomon Islands Dollar", code = "SBD", rate = 8.989098),
        SaveCurrency(name = "Seychellois Rupee", code = "SCR", rate = 14.283869),
        SaveCurrency(name = "South Sudanese Pound", code = "SDG", rate = 648.813883),
        SaveCurrency(name = "Swedish Krona", code = "SEK", rate = 11.516024),
        SaveCurrency(name = "Singapore Dollar", code = "SGD", rate = 1.429425),
        SaveCurrency(name = "Saint Helena Pound", code = "SHP", rate = 0.825367),
        SaveCurrency(name = "Sierra Leonean Leone", code = "SLE", rate = 24.489603),
        SaveCurrency(name = "Sierra Leonean Leone", code = "SLL", rate = 22619.230369),
        SaveCurrency(name = "Somali Shilling", code = "SOS", rate = 616.578671),
        SaveCurrency(name = "Surinamese Dollar", code = "SRD", rate = 37.028719),
        SaveCurrency(name = "São Tomé and Príncipe Dobra", code = "STD", rate = 22326.353608),
        SaveCurrency(name = "Salvadoran Colón", code = "SVC", rate = 9.439488),
        SaveCurrency(name = "Syrian Pound", code = "SYP", rate = 2710.198603),
        SaveCurrency(name = "Somali Shilling", code = "SOS", rate = 616.578671),
        SaveCurrency(name = "Surinamese Dollar", code = "SRD", rate = 37.028719),
        SaveCurrency(name = "São Tomé and Príncipe Dobra", code = "STD", rate = 22326.353608),
        SaveCurrency(name = "Salvadoran Colón", code = "SVC", rate = 9.439488),
        SaveCurrency(name = "Syrian Pound", code = "SYP", rate = 2710.198603),
        SaveCurrency(name = "Swazi Lilangeni", code = "SZL", rate = 19.113739),
        SaveCurrency(name = "Thai Baht", code = "THB", rate = 36.409536),
        SaveCurrency(name = "Tajikistani Somoni", code = "TJS", rate = 11.489515),
        SaveCurrency(name = "Turkmenistani Manat", code = "TMT", rate = 3.786142),
        SaveCurrency(name = "Tunisian Dinar", code = "TND", rate = 3.341733),
        SaveCurrency(name = "Tongan Paʻanga", code = "TOP", rate = 2.526363),
        SaveCurrency(name = "Turkish Lira", code = "TRY", rate = 36.98899),
        SaveCurrency(name = "Trinidad and Tobago Dollar", code = "TTD", rate = 7.311632),
        SaveCurrency(name = "New Taiwan Dollar", code = "TWD", rate = 34.627934),
        SaveCurrency(name = "Tanzanian Shilling", code = "TZS", rate = 2933.990628),
        SaveCurrency(name = "Ukrainian Hryvnia", code = "UAH", rate = 44.621328),
        SaveCurrency(name = "Ugandan Shilling", code = "UGX", rate = 3953.978902),
        SaveCurrency(name = "United States Dollar", code = "USD", rate = 1.078673),
        SaveCurrency(name = "Uruguayan Peso", code = "UYU", rate = 44.895175),
        SaveCurrency(name = "Uzbekistan Som", code = "UZS", rate = 13793.100632),
        SaveCurrency(name = "Venezuelan Bolívar Fuerte", code = "VEF", rate = 3907549.669586),
        SaveCurrency(name = "Sovereign Bolivar", code = "VES", rate = 44.962487),
        SaveCurrency(name = "Vietnamese Đồng", code = "VND", rate = 27301.214046),
        SaveCurrency(name = "Vanuatu Vatu", code = "VUV", rate = 128.06226),
        SaveCurrency(name = "Samoan Tala", code = "WST", rate = 3.021562),
        SaveCurrency(name = "CFA Franc BEAC", code = "XAF", rate = 655.284517),
        SaveCurrency(name = "Silver (troy ounce)", code = "XAG", rate = 0.031978),
        SaveCurrency(name = "Gold (troy ounce)", code = "XAU", rate = 0.000396),
        SaveCurrency(name = "East Caribbean Dollar", code = "XCD", rate = 2.915168),
        SaveCurrency(name = "Special Drawing Rights", code = "XDR", rate = 0.810883),
        SaveCurrency(name = "CFA Franc BCEAO", code = "XOF", rate = 655.29362),
        SaveCurrency(name = "CFP Franc", code = "XPF", rate = 119.331742),
        SaveCurrency(name = "Yemeni Rial", code = "YER", rate = 270.072735),
        SaveCurrency(name = "South African Rand", code = "ZAR", rate = 19.096881),
        SaveCurrency(name = "Zambian Kwacha (pre-2013)", code = "ZMK", rate = 9709.355478),
        SaveCurrency(name = "Zambian Kwacha", code = "ZMW", rate = 28.723789),
        SaveCurrency(name = "Zimbabwean Dollar", code = "ZWL", rate = 347.332271)
    )
)